### ISSUE TITLE
suggestion list that is showed to the user is always one step back to the real suggestion

### ISSUE THREAD

**Issue by khoramshahy** [prakhar1989/react-tags#574] opened 2019-12-11 09:05 UTC
Hi 
my list of suggestions is too long so I want whenever user types I get a new suggestion List from server. I'm using handleInputChange for doing that. but suggetion is always one step back.
Am I using the right function?
If not what should I do?

**Comment by dcsaszar** [comment] 2019-12-21 16:06
Maybe a duplicate of #508

**Closed** 2019-12-22 08:22 UTC
