### ISSUE TITLE
[Bug] autocomplete doesn't work

### ISSUE THREAD

**Issue by anhmt90** [prakhar1989/react-tags#353] opened 2018-06-22 12:49 UTC
After setting the `autocomplete ` prop, `Error: query.toLowerCase is not a function` occurs.

![image](https://user-images.githubusercontent.com/16328682/41777206-e09008c4-762a-11e8-8474-5e9983eebf75.png)

**Comment by ad1992** [comment] 2018-06-23 11:03
@anhmt90 this bug is duplicate of https://github.com/prakhar1989/react-tags/issues/342 and has been fixed. This will be pushed in next version release.
closing this.

**Closed by ad1992** 2018-06-23 11:03 UTC
